### ISSUE TITLE
[BUG] System.InvalidOperationException: Maximum object size exceeded

### ISSUE THREAD

**Issue by anGie44** [tj-actions/changed-files#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When running the action in our workflow, we are often seeing the error `Error: The template is not valid. System.InvalidOperationException: Maximum object size exceeded`

The action is used as follows:
https://github.com/hashicorp/terraform-provider-aws/blob/28802c652e04814ed25a7b563bd01bafd875231e/.github/workflows/terraform_provider.yml#L219-L221

### To Reproduce

1. Add the step in your github action workflow to run on a repository like the `hashicorp/terraform-provider-aws` which contains a large collection of files
2. On pull_request triggers, the step can often (not always) fail with the above error

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The step should succeed with the outputs available in subsequent steps within the workflow.

### Relevant log output

```shell
Run tj-actions/changed-files@v20.2
Run # "Set base sha..."
Run # "Calculating the previous and current SHA..."
changed-files-diff-sha
Run tj-actions/glob@v7.20
/usr/bin/git rev-parse --show-toplevel
/home/runner/work/terraform-provider-aws/terraform-provider-aws
/usr/bin/git diff --diff-filter=D --name-only eb182a5ad78b25979cdedb415053bb31a8f985ad fd447b487b74c3922206380f47a3cde1b5806164

Run bash $GITHUB_ACTION_PATH/entrypoint.sh
changed-files
Error: The template is not valid. System.InvalidOperationException: Maximum object size exceeded
   at GitHub.DistributedTask.ObjectTemplating.TemplateMemory.AddBytes(Int32 bytes)
   at GitHub.DistributedTask.ObjectTemplating.TemplateUnraveler.AllowScalar(Boolean expand, ScalarToken& scalar)
   at GitHub.DistributedTask.ObjectTemplating.TemplateEvaluator.Evaluate(DefinitionInfo definition)
   at GitHub.DistributedTask.ObjectTemplating.TemplateEvaluator.HandleMappingWithWellKnownProperties(DefinitionInfo definition, List`1 mappingDefinitions, MappingToken mapping)
   at GitHub.DistributedTask.ObjectTemplating.TemplateEvaluator.Evaluate(DefinitionInfo definition)
   at GitHub.DistributedTask.ObjectTemplating.TemplateEvaluator.HandleMappingWithAllLooseProperties(DefinitionInfo mappingDefinition, DefinitionInfo keyDefinition, DefinitionInfo valueDefinition, MappingToken mapping)
   at GitHub.DistributedTask.ObjectTemplating.TemplateEvaluator.Evaluate(DefinitionInfo definition)
   at GitHub.DistributedTask.ObjectTemplating.TemplateEvaluator.Evaluate(TemplateContext context, String type, TemplateToken template, Int32 removeBytes, Nullable`1 fileId, Boolean omitHeader)
```

### Anything else?

References: https://github.com/hashicorp/terraform-provider-aws/runs/6598628116?check_suite_focus=true

Workarounds: revert to using `v19`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@anGie44 Thanks for reporting this issue it should be resolved in the latest [v21](https://github.com/tj-actions/changed-files/releases/v21) release.
